  version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/node:latest # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run: yarn install
        - run: export  # run the `echo` command
