version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:latest
    steps:
      #- checkout
      - restore_cache:
          keys: v1-deps-nkHL0j2gThbhDPpGM0eMHg6sujg7Urs96z3u0DcAp9E=
      - run: echo "build"

