version: 2.1
jobs:
  build:
    docker: 
      - image: jekyll/jekyll:latest #circleci/ruby:latest-node
      - docker_layer_caching: true
    steps:
      - checkout
      - run: echo "build"
      - run: gem -v && bundle -v && npm -v && node -v
      #- save_cache:
      #    key: cache-key-{{ .BuildNum }}
      #    paths:
      #      - package.json      
  hold:
  test:
    docker: 
      - image: andreysenov/firebase-tools
    steps:
      #- restore_cache:
      #    key: cache-key-
      - run: echo "hold"
      - run: firebase -h
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
      - hold:
          type: approval
          requires: 
            - build
      - test:
          requires:
            - hold
          
