version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:latest
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: echo "build"
      - save_cache:
          key: cache-key-{{ .BuildNum }}
          paths:
            - package.json
      - run: npm -v && gem -v && bundle -v
  test:
    docker: 
      - image: circleci/node:latest # the primary container, where your job's commands are run
    steps:
      - restore_cache:
          key: cache-key-
      - run: echo "test" 
      
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
