version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:latest      
    steps:
      - checkout
      - run: echo "build"
      - save_cache:
          key: cache-key-{{ .BuildNum }}
          paths:
            - package.json      
  test:
    docker: 
      - image: circleci/ruby:latest
    steps:
      - restore_cache:
          key: cache-key-
      - run: echo "test" 
      - run: gem -v && bundle -v      
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
