version: 2.1
  jobs:
    aaa:
      docker: 
        - image: circleci/node:latest # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run: npm install gatsby-cli
        - run: yarn gatsby new gatsby-site
        - run: cd gatsby-site && yarn gatsby build
        #- store_artifacts:
         #   path: gatsby-site/public

workflows:
  version: 2
  workflow:
    jobs:
      - aaa
